version: '3.8'
services:
  employee-service:
    build:
      context: .
      dockerfile: Dockerfile-employee-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/employee_db
      - CLIENT_DEPARTMENT_BASE_URL=http://department-service:8082
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - SPRING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS=broker:29092
    depends_on:
      - db
      - broker
  email-service:
    build:
      context: .
      dockerfile: Dockerfile-email-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/employee_db
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - SPRING_MAIL_HOST=mailhog

    depends_on:
      - db
      - broker
      - mailhog
  department-service:
    build:
      context: .
      dockerfile: Dockerfile-department-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/employee_db
    depends_on:
      - db
  security-service:
    build:
      context: .
      dockerfile: Dockerfile-security-service
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/employee_db
    depends_on:
      - db

  db:
    image: postgres:11.5
    restart: always
    container_name: postgres_container2
    ports:
      - "5555:5432"

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

    volumes:
      - ./infastructure/db:/docker-entrypoint-initdb.d

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
